version: '3'
services:
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ALLOW_EMPTY_PASSWORD: true
  backend:
    image: registry.gitlab.com/rsamigullin/dev-tools-simple-ci/master/service-backend
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/employees"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  frontend: 
    image: registry.gitlab.com/rsamigullin/dev-tools-simple-ci/master/service-frontend
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "80:80"
    restart: always