version: '3'
services:
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ALLOW_EMPTY_PASSWORD: true
  backend:
    build: ./springboot-backend
    restart: always
    ports:
      - "8080:8080"
  frontend: 
    build: ./react-frontend
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
    ports:
      - "80:80"
  # nginx-proxy:

    # environment:
    #   - name=value
  # front